fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#
#login:
#  path: /login
#  controller: fos_user.security.controller::loginAction

logout:
  path: /logout
  controller: fos_user.security.controller::logoutAction



index:
  path: /
  controller: App\Controller\HomeController::index